/*
 * Copyright (c) Huawei Device Co., Ltd. 2026. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export const enum ConfigData {
  WH_100_100 = '100%',
  WH_60_100 = '60%',
  WH_50_100 = '50%',
  WH_40_100 = '40%',
  WH_30_100 = '30%',
  WH_20_100 = '20%',
  WH_424_VP = '424vp',
  WH_612_VP = '612vp',
  WH_560_VP = '560vp',
  WH_720_VP = '720vp',
  QH_0_VP = '0vp',
  QH_105_VP = '105vp',
  QH_150_VP = '150vp',
  QH_256_VP = '256vp',
  QH_204_VP = '204vp',
  QH_432_VP = '432vp',
  QH_372_VP = '372vp',
  QH_350_VP = '350vp',
  QH_290_VP = '290vp',
  FileType = '.m4a',
  FileTypePCM = '.pcm',
  FileTypeWAV = '.wav',
  JsonFileType = '.json',
}