/*
 * Copyright (c) Huawei Device Co., Ltd. 2026. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum Keyword {
  AGREE = '同意',
  ALLOW = '允许',
  ALLOW_FOR_THIS_USING = '本次使用允许',
  ALLOW_ONLY_DURING_USING = '仅使用期间允许',
  CALL_RECORDING = '通话录音',
  CANCEL = '取消',
  CLOSE = '关闭',
  CONFIRM = '确认',
  DELETE = '删除',
  DELETE_RECORD = '录音将从本设备中删除，可在“最近删除”中保留 30 天。',
  DESELECT_ALL = '取消全选',
  DETAIL = '详情',
  MARK = '标记',
  MORE = '更多',
  MULTI_SELECT = '多选',
  RECORDING = '录音',
  RENAME = '重命名',
  SELECT_ALL = '全选',
  SHARE = '分享',
  SOUND_RECORDER = '录音机',
  NEXT_STEP = '下一步',
  RECENTLY_DELETED = '最近删除',
  RECORDING_DELETE = '永久删除',
  FOREVER_DELETE_TIPS = '录音将从本设备永久删除，无法恢复。是否删除？',
  RESTORE = '恢复',
  DELETE_ALL = '全部删除',
  RESTORE_ALL = '全部恢复',
  KNOWN = '知道了',
  APP_SETTINGS = '设置',
  CHILD_MODE = '未成年人模式',
  NOTIFICATION = '通知',
  TOP_SHOW_NOTIFICATION = '置顶显示通知',
}
