/*
 * Copyright (c) Huawei Device Co., Ltd. 2026. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export { FormsManager } from './src/main/ets/manager/FormsManager';
export { FormDbManager } from './src/main/ets/storage/FormDbManager';
export { FormUpdateUtil } from './src/main/ets/utils/FormUpdateUtil';
export { default as Record2x1FormController } from './src/main/ets/controller/Record2x1FormController';
export { default as Record2x2FormController } from './src/main/ets/controller/Record2x2FormController';
export { default as IFormController } from './src/main/ets/controller/IFormController';
export {
  FORM_PARAM_DIMENSION_KEY,
  FORM_PARAM_IDENTITY_KEY,
  FORM_PARAM_NAME_KEY
} from './src/main/ets/constants/FormConstants';
