/*
 * Copyright (c) Huawei Device Co., Ltd. 2026. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const FORM_PARAM_IDENTITY_KEY = 'ohos.extra.param.key.form_identity';

export const FORM_PARAM_DIMENSION_KEY = 'ohos.extra.param.key.form_dimension';

export const FORM_PARAM_WIDTH_KEY = 'ohos.extra.param.key.form_width';

export const FORM_PARAM_HEIGHT_KEY = 'ohos.extra.param.key.form_height';

export const FORM_PARAM_NAME_KEY = 'ohos.extra.param.key.form_name';

/**
 * 卡片错误码集合
 */
export enum FormCardErrorCode {
  // 卡片不存在
  CARD_NOT_EXIST = 16501001
}